### ISSUE TITLE
Build funktioniert nicht unter Node.js v18.17.0

### ISSUE THREAD

**Issue by dpleipold** [Edirom/eHinman#49]
* CollAna-Commit: 683931aebf366b15f861726d710e2164bc696a85
* OS: Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-146-generic x86_64)
* Node.js: v18.17.0 LTS
* npm: v9.8.1
* Ausgabe von ```ng v```:
```
Angular CLI: 8.3.29
Node: 18.17.0
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.29
@angular-devkit/build-angular     0.803.29
@angular-devkit/build-optimizer   0.803.29
@angular-devkit/build-webpack     0.803.29
@angular-devkit/core              8.3.29
@angular-devkit/schematics        8.3.29
@angular/cdk                      8.2.3
@angular/cli                      8.3.29
@angular/flex-layout              8.0.0-beta.27
@angular/http                     7.2.16
@ngtools/webpack                  8.3.29
@schematics/angular               8.3.29
@schematics/update                0.803.29
rxjs                              6.6.3
typescript                        3.5.3
webpack                           4.39.2
```

```npm install``` bricht ab mit Fehlermeldung
```
code ERESOLVE
ERESOLVE unable to resolve dependency tree

While resolving: CollAna@0.1.0-alpha
Found: @angular/common@12.2.17
node_modules/@angular/common
  @angular/common@"^12.2.16" from the root project

Could not resolve dependency:
peer @angular/common@"^15.0.2" from ng-cdbangular@1.2.1
node_modules/ng-cdbangular
  ng-cdbangular@"^1.2.1" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

```npm install --force``` funktioniert. Danach brechen aber sowohl ```ng build``` als auch ```ng serve``` mit dieser Fehlermeldung ab:
```
Compiling @angular/cdk/drag-drop : es2015 as esm2015
⠹ Generating browser application bundles (phase: building)...node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/opt/CollAna/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/opt/CollAna/node_modules/webpack/lib/util/createHash.js:46:50)
    at SourceMapSource.updateHash (/opt/CollAna/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:231:8)
    at NormalModule._initBuildHash (/opt/CollAna/node_modules/webpack/lib/NormalModule.js:880:17)
    at handleParseResult (/opt/CollAna/node_modules/webpack/lib/NormalModule.js:946:10)
    at /opt/CollAna/node_modules/webpack/lib/NormalModule.js:1040:4
    at processResult (/opt/CollAna/node_modules/webpack/lib/NormalModule.js:755:11)
    at /opt/CollAna/node_modules/webpack/lib/NormalModule.js:819:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

Es scheint sich um ein Kompatibilitätsproblem zwischen Webpack und OpenSSL zu handeln, vergleiche [https://stackoverflow.com/q/69692842](https://stackoverflow.com/q/69692842).

Ein Downgrade auf Node.js v16.20.1 löst das Problem vorübergehend.

**Comment by AnastasiaWawilow** [comment]
Danke für den ausführlichen Bug-Report! 

Das Problem ist bekannt und hat zwei Ursachen:

1. ng-cdbangular Konflikt
ng-cdbangular@1.2.1 erfordert @angular/common@^15, ist also inkompatibel mit Angular 12. Dieses Problem ist mit dem Update auf Angular 14 behoben – bitte die aktuelle Version aus dem develop-Branch verwenden.

2. ERR_OSSL_EVP_UNSUPPORTED
Angular 12 + Webpack 4 sind nicht kompatibel mit Node.js 18. Mit Angular 14 entfällt dieses Problem, da Node 18 nativ unterstützt wird.

➡️ Lösung: Bitte auf den aktuellen develop-Branch wechseln:

bash
Copy
```
git pull
npm install --legacy-peer-deps
ng serve
```
Falls noch Probleme auftreten, bitte hier melden!
